development:
  adapter: mysql2
  socket: /var/run/mysqld/mysqld.sock
  host: localhost
  username: root
  password: root
  database: mavsgogreen
  port: 3306
  pool: 5
  timeout: 5000
  encoding: utf8